version: '3'
services:
  mysql8:
    image: dirgar/mysql8:01
    container_name: mysql8db
    volumes:
      - /apps/volumes/mysql8/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"